### ISSUE TITLE
Regions api asking `You must be authenticated to view this.`

### ISSUE THREAD

**Issue by nicholasoxford** [supabase/fly-admin#12]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When calling regions api, an error is thrown about not being authenticated. When I call another api, like list machines, it works.

## To Reproduce

``` ts
const regions = await fly.Regions.getRegions();
console.log(regions);
 ```

## Expected behavior

A list of locations should be returned, although I am grabbing the users api key from `fly auth token` via the CLI. I wonder if that token needs elevated permissions 

## Additional context

Also, @sweatybridge it is nice to meet you 👋 I am super interested in helping maintain this project. Let me know if you ever need help with something!

**Comment by nicholasoxford** [comment]
I am also not asking you to fix this bug lol, its my code. Just maybe if you have an idea why it would be failing on seemingly authentication while other calls worked. I looked at code that calls the graphql api and I couldn't find any difference s

**Comment by pcnc** [comment]
Hi @nicholasoxford 👋 nice to meet you!

You're right - it's very odd as using the same token on https://api.fly.io/graphql with the exact same query as defined in-code works without a hitch 🤔 Will be looking into this in the following couple of days

**Comment by nicholasoxford** [comment]
Let me know if I can help in any way

I will make a lot more PRs to this repo, I just got a bit trepidatious after messing up in my first one lol

**Comment by pcnc** [comment]
@nicholasoxford  - I think I've found the issue - GraphQL requests had their API key populated from the env vars, not the `apiKey` private member of the client class 

PR here: https://github.com/supabase/fly-admin/pull/17

Feel free to further contribute with whatever you'd like to the codebase!
